[package]
name = "arcade"
version = "0.0.0"
edition = "2024_07"
cairo-version = "2.11.4"

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0-alpha.1" }
cairo_test = "2.11.4"

[workspace]
members = [
    "packages/achievement",
    "packages/collection",
    "packages/controller",
    "packages/provider",
    "packages/registry",
    "packages/social",
]
description = "Dojo achievement library"
homepage = "https://github.com/cartridge-gg/arcade/"
cairo-version = "2.11.4"

[workspace.package]
version = "0.0.0"
edition = "2024_07"

[workspace.dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0-alpha.1" }
dojo_macros = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0-alpha.1" }
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0-alpha.1" }
graffiti = { git = "https://github.com/bal7hazar/graffiti.git", rev = "e8b0854" }
starknet = "2.11.4"
cairo_test = "2.11.4"

[workspace.tool.fmt]
sort-module-level-items = true
